os:
  - linux

language: php

php:
  - '7.4'

before_install:
  - composer self-update
  - composer validate
  - yes '' | pecl install -f apcu
  - yes '' | pecl install -f msgpack

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --testsuite=unit
  - vendor/bin/phpunit --testsuite=integration
